# -*- coding: utf-8 -*-
"""HW1_AARYAFarheen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MbWbNbG81yYjVn62uL0-z_SIQLXpiT-d

# ML Homework 1 Guide

1. Save a copy of this ipynb file in your GoogleDrive or PC.
2. Edit the name of this code from "HW1.ipynb" to "HW1_(your name).ipynb"
3. Fill out the code cells below according to descriptions.
4. Save and upload to BrightSpace. (DO NOT clear the outputs of your code)
5. Convert the .ipynb file to PDF file and upload together

# [HW 1-1] Data Indexing
Extract sensor signal (without time column) from 0.02 seconds to 0.12 seconds by indexing the ExampleData in Github.

* Data link: 'https://github.com/purduelamm/purdue_me597_iiot/blob/main/ml_tutorial/ML1/ExampleData?raw=true'
* Index the data as DataFrame format
* Refer to ML1_Code1
"""

# Import the necessary packages
import numpy       as np
import pandas      as pd
import matplotlib.pyplot as plt

# Load ExampleData from Github
Path = 'https://github.com/purduelamm/purdue_me597_iiot/blob/main/ml_tutorial/ML1/ExampleData?raw=true'
data = pd.read_csv(Path, sep=',',names=['time(s)', 'Acceleration(g)', 'Voltage(V)', 'Current(kA)'])
data

# Data indexing
Sensordata = data.iloc[:,1:]
Sensordata

StartPoint = np.where(data.iloc[:,0].values == 0.02)[0][0]
EndPoint   = np.where(data.iloc[:,0].values == 0.12)[0][0]

StartPoint, EndPoint

SensorData=Sensordata.iloc[StartPoint:EndPoint+1,:]
SensorData

"""# [HW 1-2] Data Processing & Plotting
Plot the change in mean value every 0.01 seconds for each sensor signal in 'SensorData' above.
* Refer to ML1_Code3
"""

# Feature extraction
mean1 = np.mean(SensorData.iloc[:,0])
mean2 = np.mean(SensorData.iloc[:,1])
mean3 = np.mean(SensorData.iloc[:,2])
meanvalue =np.array([mean1,mean2,mean3])
meanvalue

meanvalue=np.zeros((1,SensorData.shape[1]))
meanvalue

meanvalue = np.zeros((1, SensorData.shape[1])) # Re-initialize meanvalue with correct shape based on SensorData

for i in range(SensorData.shape[1]):
    meanvalue[0,i]=np.mean(SensorData.iloc[:,i]) # Calculate mean for each column
meanvalue

mean_value = np.zeros((11, SensorData.shape[1]))



for sensor in range(SensorData.shape[1]):
    for time in range(11):
        mean_value[time, sensor] = np.mean(
           SensorData.iloc[time*128:(time+1)*128, sensor]
        )
mean_value

TimeArr = np.arange(2,13)/100
print(TimeArr.shape)
TimeArr

# Plot graphs
plt.figure(figsize=(10, 5))
plt.plot(TimeArr, mean_value[:, 0], label='Acceleration',ls = '--', c = 'r', marker = 'x', ms = 6, mfc = 'r', mec = 'r')
plt.plot(TimeArr, mean_value[:, 1], label='Voltage',ls = '--', c = 'g', marker = 'o', ms = 5, mfc = 'g', mec = 'g')
plt.plot(TimeArr, mean_value[:, 2], label='Current',ls = '--', c = 'b', marker = '*', ms = 8, mfc = 'b', mec = 'b')
plt.legend()
plt.xlabel('Time (s)')
plt.ylabel('Mean Value')
plt.title('Mean Value vs Time')
plt.grid(True,c='lightgrey')
plt.show()

"""## ML1 and ML2 Summary and Deliverables

Answer the following questions for your achievements

### Q1. Please summarize ML1 and ML2.

---
We learned how to import packages, read CSV files from GitHub, index and filter datasets, and save and plot the data. We also explored creating arrays and using array and DataFrame functions to modify and access data efficiently.
---

### Q2. What skills did you have to develop to accomplish this project?

---

I developed skills in Python programming, data handling with pandas and NumPy, and visualizing data with Matplotlib.

---

### Q3. What aspects of this project were the most beneficial for your learning?

---

The most beneficial aspects were learning to manipulate and analyze datasets, filter and process data efficiently, and visualize results clearly, which strengthened both my programming and data analysis skills

---

### Q4. What challenges did you encounter in completing the project?

---

The main challenges were correctly indexing the data and extracting the required features from large datasets. Ensuring the slices and calculations aligned with the intended time windows or columns required careful attention.

---

### Q5. How did you overcome the challenges or remedy the problems encountered?

---

I overcame the challenges by carefully reviewing the dataset structure, using systematic indexing, and testing small data segments before applying operations to the full dataset. I also referred to documentation and examples to correctly extract and compute the features.

---
"""